### PR TITLE
clarifying that this workbook is for 1GP

### PR DESCRIPTION
**Pull request by jamesquinn103**

### CODE REVIEW

**Comment by jamesquinn103** [comment]
@VivekMChawla this UI text change is ready for your review, thanks!

**Comment by VivekMChawla** [comment]
@jamesquinn103 How do you feel about the phrase "Managed 1GP" instead of "First-Generation Managed Packages (1GP).

**Comment by jamesquinn103** [comment]
> @jamesquinn103 How do you feel about the phrase "Managed 1GP" instead of "First-Generation Managed Packages (1GP).

Sounds good to me! I'll make that change @VivekMChawla

**Comment by jamesquinn103** [comment]
@VivekMChawla I have made that verbiage change in all 3 parts that I made UI text changes to: top & side nav + title of first page, thanks!

**Comment by VivekMChawla** [comment]
@jamesquinn103 - Sorry, I should have used the full text of "Building Managed 1GP with Salesforce DX" to clarify my suggestion.  Could we go with that verbiage instead?

**Comment by jamesquinn103** [comment]
@VivekMChawla no worries, done!

**Review by VivekMChawla — APPROVED** [review]

**Review by VivekMChawla — APPROVED** [review]

**Pull request merged**
